name: Ejecutar Encuesta Satisfacción

on:
  schedule:
    - cron: "25 5 * * *"   # todos los días a las 00:25 AM hora Colombia (05:25 UTC)
  workflow_dispatch:         # también puedes lanzarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python main.py
